# Generated by Django 3.2.12 on 2022-02-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
